#!/usr/bin/env bash
set -euo pipefail

# ─── Local Validation Script ───────────────────────────────────────────────────
# Builds and runs hausparty locally against the dev cluster environment.
#
# Modes:
#   (default)   Build Docker image and run container
#   --dev       Generate .env.local and run npm run dev
#
# Prerequisites:
#   - bws CLI installed with BWS_ACCESS_TOKEN in repo root .env
#   - kubectl configured (KUBECONFIG set to talos/kubeconfig)
#   - Docker (for default mode) or Node.js (for --dev mode)
#   - Keycloak dev realm must have http://localhost:3000/* as a valid redirect URI
# ────────────────────────────────────────────────────────────────────────────────

MODE="docker"
[[ "${1:-}" == "--dev" ]] && MODE="dev"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"

# ─── Bitwarden Secret UUIDs (match dev cluster ExternalSecrets) ─────────────
BWS_AUTH_KEYCLOAK_SECRET="dfc135ab-56bd-42e6-83a8-b4230112ea1e"
BWS_AUTH_SECRET="09512667-d3ec-46d7-8c42-b4230112ea3f"
BWS_PG_PASSWORD="c75e6775-a630-4213-9086-b4230112e9f8"
BWS_ADMIN_API_KEY="c5f03b67-e4d8-4888-99aa-b416000ff1b7"
BWS_EDMTRAIN_API_KEY="f336e797-bc78-4f2b-959e-b416000ff293"

# ─── Static env vars (match dev cluster values.yaml) ───────────────────────
AUTH_KEYCLOAK_ID="hausparty"
AUTH_KEYCLOAK_ISSUER="https://sso.dev.techgarden.gg/realms/hausparty"
AUTH_URL="http://localhost:3000"
AUTH_TRUST_HOST="true"
PG_PORT="5432"
PG_DB="hausparty"
PG_USER="hausparty_app"

# ─── Preflight checks ──────────────────────────────────────────────────────
check_cmd() {
  if ! command -v "$1" &>/dev/null; then
    echo "ERROR: $1 is required but not found" >&2
    exit 1
  fi
}

check_cmd bws
check_cmd kubectl
check_cmd jq
if [[ "$MODE" == "docker" ]]; then
  check_cmd docker
else
  check_cmd npm
fi

# ─── Source BWS token ───────────────────────────────────────────────────────
if [[ -z "${BWS_ACCESS_TOKEN:-}" ]]; then
  if [[ -f "$REPO_ROOT/.env" ]]; then
    # shellcheck source=/dev/null
    source "$REPO_ROOT/.env"
  fi
fi

if [[ -z "${BWS_ACCESS_TOKEN:-}" ]]; then
  echo "ERROR: BWS_ACCESS_TOKEN not set. Add it to $REPO_ROOT/.env or export it." >&2
  exit 1
fi
export BWS_ACCESS_TOKEN

# ─── Fetch secrets from Bitwarden ──────────────────────────────────────────
echo "Fetching secrets from Bitwarden SecretManager..."
AUTH_KEYCLOAK_SECRET="$(bws secret get "$BWS_AUTH_KEYCLOAK_SECRET" | jq -r .value)"
AUTH_SECRET="$(bws secret get "$BWS_AUTH_SECRET" | jq -r .value)"
PG_PASSWORD="$(bws secret get "$BWS_PG_PASSWORD" | jq -r .value)"
ADMIN_API_KEY="$(bws secret get "$BWS_ADMIN_API_KEY" | jq -r .value)"
EDMTRAIN_API_KEY="$(bws secret get "$BWS_EDMTRAIN_API_KEY" | jq -r .value)"
echo "Secrets fetched."

# ─── Port-forward dev cluster database ─────────────────────────────────────
PF_PID=""
cleanup() {
  if [[ -n "$PF_PID" ]]; then
    kill "$PF_PID" 2>/dev/null || true
    wait "$PF_PID" 2>/dev/null || true
    echo "Port-forward stopped."
  fi
}
trap cleanup EXIT

echo "Starting port-forward to hausparty-db-rw..."
kubectl port-forward -n hausparty svc/hausparty-db-rw 5432:5432 &>/dev/null &
PF_PID=$!
sleep 2

# Verify port-forward is running
if ! kill -0 "$PF_PID" 2>/dev/null; then
  echo "ERROR: Port-forward failed to start. Check kubectl access to 1276-dev cluster." >&2
  exit 1
fi
echo "Port-forward active (PID $PF_PID)."

# ─── Keycloak reminder ────────────────────────────────────────────────────
echo ""
echo "NOTE: Keycloak dev realm must have http://localhost:3000/* as a valid"
echo "      redirect URI. Configure at: https://sso.dev.techgarden.gg/admin"
echo ""

# ─── Run ───────────────────────────────────────────────────────────────────
if [[ "$MODE" == "docker" ]]; then
  echo "Building Docker image..."
  docker build -t hausparty:local "$APP_DIR"

  echo "Running container on http://localhost:3000 ..."
  docker run --rm -p 3000:3000 \
    --add-host=host.docker.internal:host-gateway \
    -e AUTH_KEYCLOAK_ID="$AUTH_KEYCLOAK_ID" \
    -e AUTH_KEYCLOAK_SECRET="$AUTH_KEYCLOAK_SECRET" \
    -e AUTH_KEYCLOAK_ISSUER="$AUTH_KEYCLOAK_ISSUER" \
    -e AUTH_URL="$AUTH_URL" \
    -e AUTH_TRUST_HOST="$AUTH_TRUST_HOST" \
    -e AUTH_SECRET="$AUTH_SECRET" \
    -e PG_HOSTNAME=host.docker.internal \
    -e PG_PORT="$PG_PORT" \
    -e PG_DB="$PG_DB" \
    -e PG_USER="$PG_USER" \
    -e PG_PASSWORD="$PG_PASSWORD" \
    -e ADMIN_API_KEY="$ADMIN_API_KEY" \
    -e EDMTRAIN_API_KEY="$EDMTRAIN_API_KEY" \
    hausparty:local

else
  # Dev mode: generate .env.local and run npm run dev
  ENV_FILE="$APP_DIR/.env.local"
  cat > "$ENV_FILE" <<EOF
# Generated by local-validate.sh — do not commit
AUTH_KEYCLOAK_ID=$AUTH_KEYCLOAK_ID
AUTH_KEYCLOAK_SECRET=$AUTH_KEYCLOAK_SECRET
AUTH_KEYCLOAK_ISSUER=$AUTH_KEYCLOAK_ISSUER
AUTH_URL=$AUTH_URL
AUTH_TRUST_HOST=$AUTH_TRUST_HOST
AUTH_SECRET=$AUTH_SECRET
PG_HOSTNAME=localhost
PG_PORT=$PG_PORT
PG_DB=$PG_DB
PG_USER=$PG_USER
PG_PASSWORD=$PG_PASSWORD
ADMIN_API_KEY=$ADMIN_API_KEY
EDMTRAIN_API_KEY=$EDMTRAIN_API_KEY
EOF
  echo ".env.local written to $ENV_FILE"
  echo "Starting dev server on http://localhost:3000 ..."
  cd "$APP_DIR" && npm run dev
fi
