// Re-export all types from the Drizzle schema module
export type {
  Genre,
  Artist,
  Festival,
  Event,
  DjSet,
  Source,
  TracklistEntry,
  SavedSet,
  Follow,
  Collection,
  Submission,
  UserRoleRow,
  ScraperRun,
  ScraperEntityMap,
  UserSettings,
  Platform,
  SourceType,
  MediaType,
  FollowTarget,
  SubmissionStatus,
  UserRole,
  ScraperStatus,
  SetWithDetails,
  ArtistWithGenres,
  FestivalWithGenres,
} from "@/lib/db/types";
